Repository sknooyen/UBay, pull requests merged in 2024-04, with the labels that each got.

#6 Add sell page boiler plate
  src/Sell.js
Labels: enhancement

#8 Add success alert message on sell page
  src/Sell.js
Labels: enhancement

#14 Profile page
  src/Front-end/ListingItem.js
  src/Front-end/ListingsLayout.js
  src/Front-end/Profile.js
Labels: enhancement

#16 Add individual listing page
  src/Front-end/ListingPage.js
  src/Front-end/ListingsLayout.js
  src/index.js
Labels: enhancement

#18 Add firebase to README
  README.md
Labels: documentation

#19 Heart button
  README.md
  src/Front-end/ListingPage.js
Labels: enhancement

#20 fixed sortBy issue
  src/Front-end/ListingsLayout.js
  src/Front-end/util.js
Labels: bug

#22 Fetch name and last updated date
  src/Front-end/ListingPage.js
Labels: enhancement
